import os
import sqlite3
from dotenv import load_dotenv
from langchain_community.utilities import SQLDatabase
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI

# Load environment variables from .env file
load_dotenv()

def get_db_schema():
    """Dynamically extracts table structures to give context to the LLM."""
    db = SQLDatabase.from_uri("sqlite:///saas_dashboard.db")
    return db.get_table_info()

def execute_sql_query(query: str):
    """Executes the raw SQL query generated by the LLM safely against the database."""
    conn = sqlite3.connect("saas_dashboard.db")
    cursor = conn.cursor()
    try:
        cursor.execute(query)
        results = cursor.fetchall()
        column_names = [description[0] for description in cursor.description]
        conn.close()
        return {"columns": column_names, "data": results}
    except Exception as e:
        conn.close()
        return {"error": str(e)}

def run_text_to_sql_pipeline(user_question: str):
    # 1. Initialize our lightweight, fast LLM
    llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)

    # 2. Get the up-to-date schema details
    db_schema = get_db_schema()

    # 3. Craft a secure, precise prompt instruction
    sql_generation_prompt = ChatPromptTemplate.from_messages([
        ("system", """You are a brilliant data analyst specializing in SaaS database systems. 
Given the following SQLite database schema, translate the user's natural language question into a clean, valid SQL query.

---
SCHEMA:
{schema}
---

CRITICAL RULES:
- Output ONLY the raw executable SQL query string. 
- Do NOT wrap it in markdown code blocks (like ```sql) or any introductory text.
- Use correct SQLite functions (e.g., use strftime for dates instead of MySQL's DATE_FORMAT).
- Only read data using SELECT. Do NOT perform any mutations."""),
        ("human", "Question: {question}")
    ])

    # 4. Chain the prompt together with the LLM call
    chain = sql_generation_prompt | llm
    
    # 5. Generate the raw SQL query string
    print(f"Translating question: '{user_question}'...")
    response = chain.invoke({"schema": db_schema, "question": user_question})
    generated_sql = response.content.strip()
    
    print(f"\nGenerated SQL Query:\n{generated_sql}\n")

    # 6. Run the query against our SQLite database
    db_result = execute_sql_query(generated_sql)
    
    if "error" in db_result:
        return f"Database Execution Error: {db_result['error']}"

    # 7. Synthesize the raw data rows back into natural language sentence response
    synthesis_prompt = ChatPromptTemplate.from_messages([
        ("system", "You are a helpful SaaS dashboard assistant. Take the raw database execution results and clearly explain the answer to the user's original question in plain English."),
        ("human", "User Question: {question}\nExecuted SQL: {sql}\nRaw Results: {results}")
    ])
    
    synthesis_chain = synthesis_prompt | llm
    final_answer = synthesis_chain.invoke({
        "question": user_question,
        "sql": generated_sql,
        "results": str(db_result["data"])
    })
    
    return final_answer.content

# Simple local test block
if __name__ == "__main__":
    # Test question that requires aggregations and complex groupings
    sample_question = "Which subscription plan has generated the most active accounts, and how many are there?"
    answer = run_text_to_sql_pipeline(sample_question)
    print(f"Bot Response:\n{answer}")